name: Tests

on:
  push:
    branches: [main]
    paths:
      - "src/**"
      - "tests/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "Makefile"
      - ".cargo/**"
      - ".github/workflows/pipeline.yml"
  pull_request:
    branches: [main]
    paths:
      - "src/**"
      - "tests/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "Makefile"
      - ".cargo/**"
      - ".github/workflows/pipeline.yml"

jobs:
  ci:
    name: ci (${{ matrix.toolchain }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable] # TODO: enable nightly
    env:
      RUSTFLAGS: "-C target-cpu=generic"
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Rust toolchain (rustup)
        run: |
          rustup toolchain install ${{ matrix.toolchain }} --profile minimal --component clippy --component rustfmt --component llvm-tools-preview
          rustup default ${{ matrix.toolchain }}
          rustc --version
          cargo --version

      - name: Cache Rust dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ matrix.toolchain }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-${{ matrix.toolchain }}-

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@b1d53d4d726d74b5a950a5b3798a3c6ede4e0f64 # cargo-llvm-cov

      - name: Run quality checks
        run: make quality

      - name: Upload HTML coverage report artifact for GitHub Pages
        if: github.ref == 'refs/heads/main' && matrix.toolchain == 'stable'
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: target/llvm-cov/html

  deploy:
    name: Deploy to GitHub Pages
    if: github.ref == 'refs/heads/main'
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
