name: Tests

on:
  push:
    paths:
      - 'Rudim/**'
      - 'Rudim.Test/**'
      - 'Rudim.sln'
      - '.github/workflows/pipeline.yml'
    branches: [ main ]
  pull_request:
    paths:
      - 'Rudim/**'
      - 'Rudim.Test/**'
      - 'Rudim.sln'
      - '.github/workflows/pipeline.yml'
    branches: [ main ]

jobs:
  build:
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Perft 
      run: dotnet run -c Release --perft --project='Rudim'
    - name: Test
      run: dotnet test --no-build --verbosity normal -c Release --collect:"XPlat Code Coverage"
    - name: Benchmark
      working-directory: Rudim
      run: |
        dotnet run -c Release --benchmark
        echo "$(cat BenchmarkDotNet.Artifacts/results/Rudim.Benchmark-report-github.md)" >> $GITHUB_STEP_SUMMARY
    - name: Generate Coverage Report
      run: |
        dotnet tool install --global dotnet-reportgenerator-globaltool
        reportgenerator "-reports:**/coverage.cobertura.xml" "-targetdir:coverage-report" 
    - name: Upload coverage artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: coverage-report
        name: 'coverage-report'
    - name: Deploy Coverage Report to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        artifact_name: coverage-report

